### ISSUE TITLE
Fix User Uploads Search

### ISSUE THREAD

**Issue by mediafiresp** [PXgamer/PX-Scripts#8]
The UUS only searches the first page of the uploads section of a user and returns.
it ignores the items which match on the subsequent pages.

eg. when i searched for the title "expanse" on an uploader "JoyBell"
the result was only from the first page while the first item on the next page also matched the criteria.
[screenshots below]

![1](https://cloud.githubusercontent.com/assets/20533808/16943429/586240fc-4db9-11e6-82f7-6220f6576d88.PNG)
![2](https://cloud.githubusercontent.com/assets/20533808/16943430/586f3820-4db9-11e6-8cf9-f1f78ebdd17a.PNG)

[https://greasyfork.org/en/scripts/19527-user-uploads-search/](url)

**Comment by owenvoke** [comment]
Hi, that is actually meant to be like that to stop ajax pinging, but... I might implement it cause I'm pretty sure that KAT can handle the extra requests.

**Comment by mediafiresp** [comment]
i was also looking around the settings in kat and noticed that only 200 items was the max limit for a page.. and was just thinking that it has something to do with how much kat could handle. [or limiting to not overburden.]

and thanks for getting back quickly.

**Comment by owenvoke** [comment]
200 is usually a max limit to reduce the load on the database, and to increase the page load time. But, it also requires more database queries to be run.

I'd say their servers are more than capable of handling a few more. :)

I'll work on this in a bit hopefully.
